0INSERT INTO `cantidatos`(`cand_data_geracao`, `cand_hora_geracao`, `cand_ano_eleicao`, `cand_num_turno`, `cand_descricao_eleicao`, `cand_sigla_uf`, `cand_sigla_ue`, `cand_descricao_ue`, `cand_codigo_cargo`, `cand_descricao_cargo`, `cand_nome_canditato`, `cand_sequencial_candidato`, `cand_numero_candidato`, `cand_nome_urna_candidato`, `cand_cod_situacao_candidatura`, `cand_desc_situacao_candidatura`, `cand_numero_partido`, `cand_sigla_partido`, `cand_nome_pardido`, `cand_codigo_lengenda`, `cand_sigla_lengenda`, `cand_composicao_legenda`, `cand_nome_legenda`, `cand_codigo_ocupacao`, `cand_descricao_ocupacao`, `cand_data_nascimento`, `cand_num_titulo_eleitoral_candidato`, `cand_idade_data_eleicao`, `cand_codigo_sexo`, `cand_descricao_sexo`, `cand_grau_instrucao`, `cand_descricao_grau_instrucao`, `cand_codigo_estado_civil`, `cand_descricao_estado_civil`, `cand_cor_raca`, `cand_descricao_cor_raca`, `cand_codigo_nacionalidade`, `cand_descricao_nacionalidade`, `cand_uf_nascimento`, `cand_municipio_nascimento`, `cand_nome_municipio_nascimento`, `cand_despesa_max_campanha`, `cand_sit_tot_turno`, `cand_desc_sit_tot_turno`) VALUES ('2014-08-17','20:05:53','2014','1','Eleições Gerais 2014','PA','PA',
			  'PARÁ','7','DEPUTADO ESTADUAL','ROBERTO LUIZ AMARAL DA ROCHA','140000000583','22555','ROBERTO ROCHA','4',
			  'INDEFERIDO COM RECURSO','22','PR','PARTIDO DA REPÚBLICA','140000000019','#NULO#','PR / PHS / PROS','UNIÃO PELO POVO DO PARÁ',
			  '257','EMPRESÁRIO','1966-01-01','016538091392','48','2','MASCULINO','6'
			  ,'ENSINO MÉDIO COMPLETO','3','CASADO(A)','02','PRETA','1','BRASILEIRA NATA','PA','-3'
			  ,'MARITUBA'','1500000','-1','#NULO#')<br/>INSERT INTO `cantidatos`(`cand_data_geracao`, `cand_hora_geracao`, `cand_ano_eleicao`, `cand_num_turno`, `cand_descricao_eleicao`, `cand_sigla_uf`, `cand_sigla_ue`, `cand_descricao_ue`, `cand_codigo_cargo`, `cand_descricao_cargo`, `cand_nome_canditato`, `cand_sequencial_candidato`, `cand_numero_candidato`, `cand_nome_urna_candidato`, `cand_cod_situacao_candidatura`, `cand_desc_situacao_candidatura`, `cand_numero_partido`, `cand_sigla_partido`, `cand_nome_pardido`, `cand_codigo_lengenda`, `cand_sigla_lengenda`, `cand_composicao_legenda`, `cand_nome_legenda`, `cand_codigo_ocupacao`, `cand_descricao_ocupacao`, `cand_data_nascimento`, `cand_num_titulo_eleitoral_candidato`, `cand_idade_data_eleicao`, `cand_codigo_sexo`, `cand_descricao_sexo`, `cand_grau_instrucao`, `cand_descricao_grau_instrucao`, `cand_codigo_estado_civil`, `cand_descricao_estado_civil`, `cand_cor_raca`, `cand_descricao_cor_raca`, `cand_codigo_nacionalidade`, `cand_descricao_nacionalidade`, `cand_uf_nascimento`, `cand_municipio_nascimento`, `cand_nome_municipio_nascimento`, `cand_despesa_max_campanha`, `cand_sit_tot_turno`, `cand_desc_sit_tot_turno`) VALUES ('2014-08-17','20:05:53','2014','1','Eleições Gerais 2014','PA','PA',
			  'PARÁ','7','DEPUTADO ESTADUAL','JOANA D'ARC DA SILVA SANTOS','140000000876','23330','JOANA SANTOS','4',
			  'INDEFERIDO COM RECURSO','23','PPS','PARTIDO POPULAR SOCIALISTA','140000000029','#NULO#','PPS','PARTIDO ISOLADO',
			  '171','JORNALISTA E REDATOR','1973-05-24','024481411368','41','4','FEMININO','8'
			  ,'SUPERIOR COMPLETO','3','CASADO(A)','01','BRANCA','1','BRASILEIRA NATA','SP','-3'
			  ,'SAO PAULO','2000000','-1','#NULO#')<br/>