0INSERT INTO `cantidatos`(`cand_data_geracao`, `cand_hora_geracao`, `cand_ano_eleicao`, `cand_num_turno`, `cand_descricao_eleicao`, `cand_sigla_uf`, `cand_sigla_ue`, `cand_descricao_ue`, `cand_codigo_cargo`, `cand_descricao_cargo`, `cand_nome_canditato`, `cand_sequencial_candidato`, `cand_numero_candidato`, `cand_nome_urna_candidato`, `cand_cod_situacao_candidatura`, `cand_desc_situacao_candidatura`, `cand_numero_partido`, `cand_sigla_partido`, `cand_nome_pardido`, `cand_codigo_lengenda`, `cand_sigla_lengenda`, `cand_composicao_legenda`, `cand_nome_legenda`, `cand_codigo_ocupacao`, `cand_descricao_ocupacao`, `cand_data_nascimento`, `cand_num_titulo_eleitoral_candidato`, `cand_idade_data_eleicao`, `cand_codigo_sexo`, `cand_descricao_sexo`, `cand_grau_instrucao`, `cand_descricao_grau_instrucao`, `cand_codigo_estado_civil`, `cand_descricao_estado_civil`, `cand_cor_raca`, `cand_descricao_cor_raca`, `cand_codigo_nacionalidade`, `cand_descricao_nacionalidade`, `cand_uf_nascimento`, `cand_municipio_nascimento`, `cand_nome_municipio_nascimento`, `cand_despesa_max_campanha`, `cand_sit_tot_turno`, `cand_desc_sit_tot_turno`) VALUES ('2014-08-17','20:05:53','2014','1','Eleições Gerais 2014','RO','RO',
			  'RONDÔNIA','6','DEPUTADO FEDERAL','TANIA ROSILENE DE AVILA BELLO','220000000032','4522','TANIA D'AVILA','2',
			  'DEFERIDO','45','PSDB','PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA','220000000041','#NULO#','PSDB / PSDC / PSD / PEN / SD / PHS / PSC / PMN / PT do B / PRB / DEM','FRENTE MUDA RONDÔNIA II',
			  '257','EMPRESÁRIO','1969-09-22','005550012372','45','4','FEMININO','6'
			  ,'ENSINO MÉDIO COMPLETO','1','SOLTEIRO(A)','01','BRANCA','1','BRASILEIRA NATA','MS','-3'
			  ,'CAMPO GRANDE','5000000','-1','#NULO#')<br/>INSERT INTO `cantidatos`(`cand_data_geracao`, `cand_hora_geracao`, `cand_ano_eleicao`, `cand_num_turno`, `cand_descricao_eleicao`, `cand_sigla_uf`, `cand_sigla_ue`, `cand_descricao_ue`, `cand_codigo_cargo`, `cand_descricao_cargo`, `cand_nome_canditato`, `cand_sequencial_candidato`, `cand_numero_candidato`, `cand_nome_urna_candidato`, `cand_cod_situacao_candidatura`, `cand_desc_situacao_candidatura`, `cand_numero_partido`, `cand_sigla_partido`, `cand_nome_pardido`, `cand_codigo_lengenda`, `cand_sigla_lengenda`, `cand_composicao_legenda`, `cand_nome_legenda`, `cand_codigo_ocupacao`, `cand_descricao_ocupacao`, `cand_data_nascimento`, `cand_num_titulo_eleitoral_candidato`, `cand_idade_data_eleicao`, `cand_codigo_sexo`, `cand_descricao_sexo`, `cand_grau_instrucao`, `cand_descricao_grau_instrucao`, `cand_codigo_estado_civil`, `cand_descricao_estado_civil`, `cand_cor_raca`, `cand_descricao_cor_raca`, `cand_codigo_nacionalidade`, `cand_descricao_nacionalidade`, `cand_uf_nascimento`, `cand_municipio_nascimento`, `cand_nome_municipio_nascimento`, `cand_despesa_max_campanha`, `cand_sit_tot_turno`, `cand_desc_sit_tot_turno`) VALUES ('2014-08-17','20:05:53','2014','1','Eleições Gerais 2014','RO','RO',
			  'RONDÔNIA','6','DEPUTADO FEDERAL','DORANILDA ALVES DA SILVA','220000000352','1133','PROFESSORA DORANILDA 'DÓRA'','2',
			  'DEFERIDO','11','PP','PARTIDO PROGRESSISTA','220000000017','#NULO#','PP / PR / PPS / PTC / PV / PROS','RONDÔNIA NO RUMO CERTO, DE NOVO',
			  '266','PROFESSOR DE ENSINO MÉDIO','1966-06-11','000006752305','48','4','FEMININO','8'
			  ,'SUPERIOR COMPLETO','3','CASADO(A)','03','PARDA','1','BRASILEIRA NATA','RO','-3'
			  ,'GUAJARÁ-MIRIM','2000000','-1','#NULO#')<br/>INSERT INTO `cantidatos`(`cand_data_geracao`, `cand_hora_geracao`, `cand_ano_eleicao`, `cand_num_turno`, `cand_descricao_eleicao`, `cand_sigla_uf`, `cand_sigla_ue`, `cand_descricao_ue`, `cand_codigo_cargo`, `cand_descricao_cargo`, `cand_nome_canditato`, `cand_sequencial_candidato`, `cand_numero_candidato`, `cand_nome_urna_candidato`, `cand_cod_situacao_candidatura`, `cand_desc_situacao_candidatura`, `cand_numero_partido`, `cand_sigla_partido`, `cand_nome_pardido`, `cand_codigo_lengenda`, `cand_sigla_lengenda`, `cand_composicao_legenda`, `cand_nome_legenda`, `cand_codigo_ocupacao`, `cand_descricao_ocupacao`, `cand_data_nascimento`, `cand_num_titulo_eleitoral_candidato`, `cand_idade_data_eleicao`, `cand_codigo_sexo`, `cand_descricao_sexo`, `cand_grau_instrucao`, `cand_descricao_grau_instrucao`, `cand_codigo_estado_civil`, `cand_descricao_estado_civil`, `cand_cor_raca`, `cand_descricao_cor_raca`, `cand_codigo_nacionalidade`, `cand_descricao_nacionalidade`, `cand_uf_nascimento`, `cand_municipio_nascimento`, `cand_nome_municipio_nascimento`, `cand_despesa_max_campanha`, `cand_sit_tot_turno`, `cand_desc_sit_tot_turno`) VALUES ('2014-08-17','20:05:53','2014','1','Eleições Gerais 2014','RO','RO',
			  'RONDÔNIA','7','DEPUTADO ESTADUAL','FERNANDO INACIO BARBOSA','220000000398','43333','BUDA'S','2',
			  'DEFERIDO','43','PV','PARTIDO VERDE','220000000017','#NULO#','PP / PR / PPS / PTC / PV / PROS','RONDÔNIA NO RUMO CERTO, DE NOVO',
			  '169','COMERCIANTE','1976-12-13','017704421813','37','2','MASCULINO','3'
			  ,'ENSINO FUNDAMENTAL INCOMPLETO','1','SOLTEIRO(A)','03','PARDA','1','BRASILEIRA NATA','MS','-3'
			  ,'PEDRO GOMES','1000000','-1','#NULO#')<br/>